name: Publish Docker multiplatform image

on:
  push:
    branches:
      - 'master'

jobs:
  detect-changes:
    uses: ./.github/workflows/template-detect-changes.yml
    with:
      base-ref: ${{ github.event.before }}

  docker:
    needs: detect-changes
    if: needs.detect-changes.outputs.has-images == 'true'
    uses: ./.github/workflows/template-publish.yml
    secrets: inherit
    strategy:
      matrix:
        image: ${{ fromJson(needs.detect-changes.outputs.images) }}
    with:
      image: ${{ matrix.image }}
      platform: 'linux/amd64,linux/arm64'

  docker-vapor:
    needs: detect-changes
    if: needs.detect-changes.outputs.has-vapor-images == 'true'
    uses: ./.github/workflows/template-publish.yml
    secrets: inherit
    strategy:
      matrix:
        image: ${{ fromJson(needs.detect-changes.outputs.vapor-images) }}
    with:
      image: ${{ matrix.image }}
      platform: ${{ contains(matrix.image, 'arm')  && 'linux/arm64' || 'linux/amd64' }}
      build-args: ${{ contains(matrix.image, 'arm')  && '__VAPOR_RUNTIME=docker-arm' || '' }}
