name: Publish Docker multiplatform image
on:
  push:
    branches:
      - '**'
      - '!master'
jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: ['5.6', '7.1', '7.1-xdebug', '7.2', '7.2-xdebug', '7.3', '7.4', '7.4-xdebug', '8.0', '8.0-xdebug', '8.0-prod', '8.1', '8.1-xdebug', '8.1-prod']
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build image
        uses: docker/build-push-action@v2
        with:
          context: "{{defaultContext}}:${{ matrix.image }}"
          platforms: linux/amd64,linux/arm64
          load: true
          tags: somosyampi/docker-php-fpm:${{ matrix.image }}-test
      -
        name: Test image
        run: |
          docker run --rm somosyampi/docker-php-fpm:${{ matrix.image }}-test php -i