name: Publish Docker multiplatform image
on:
  push:
    branches:
      - 'multiplatform'
jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: ['5.6', '7.1', '7.1-xdebug', '7.2', '7.2-xdebug', '7.3', '7.4', '7.4-xdebug', '7.4-wk', '8.0', '8.0-xdebug', '8.0-prod']
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: "{{defaultContext}}:${{ matrix.image }}"
          platforms: linux/amd64,linux/arm64
          push: true
          tags: somosyampi/docker-php-fpm:multiplat-${{ matrix.image }}