name: Build and test Docker multiplatform images
on:
  push:
    branches:
      - '**'
      - '!master'
jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: ['5.6', '7.1', '7.1-xdebug', '7.2', '7.2-xdebug', '7.3', '7.4', '7.4-xdebug', '8.0', '8.0-xdebug', '8.0-prod', '8.1', '8.1-xdebug', '8.1-prod']
        platform: ['linux/amd64', 'linux/arm64']
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build image
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:${{ matrix.image }}"
          platforms: "${{ matrix.platform }}"
          load: true
          tags: somosyampi/docker-php-fpm:${{ matrix.image }}-test
      -
        name: Test image
        run: |
          docker image inspect somosyampi/docker-php-fpm:${{ matrix.image }}-test
          docker run --rm somosyampi/docker-php-fpm:${{ matrix.image }}-test php -i
      -
        name: Scan for vulnerabilities
        uses: crazy-max/ghaction-container-scan@v2
        with:
          image: somosyampi/docker-php-fpm:${{ matrix.image }}-test
          annotations: true
