name: Build and test Docker multiplatform images

on:
  push:
    branches:
      - '**'
      - '!master'
  pull_request:

jobs:
  detect-changes:
    uses: ./.github/workflows/template-detect-changes.yml
    with:
      base-ref: origin/master

  docker:
    needs: detect-changes
    if: needs.detect-changes.outputs.has-images == 'true'
    uses: ./.github/workflows/template-build-test.yml
    strategy:
      matrix:
        image: ${{ fromJson(needs.detect-changes.outputs.images) }}
        platform: ['linux/amd64', 'linux/arm64']
    with:
      image: ${{ matrix.image }}
      platform: ${{ matrix.platform }}

  docker-vapor:
    needs: detect-changes
    if: needs.detect-changes.outputs.has-vapor-images == 'true'
    uses: ./.github/workflows/template-build-test.yml
    strategy:
      matrix:
        image: ${{ fromJson(needs.detect-changes.outputs.vapor-images) }}
    with:
      image: ${{ matrix.image }}
      platform: ${{ contains(matrix.image, 'arm')  && 'linux/arm64' || 'linux/amd64' }}
      build-args: ${{ contains(matrix.image, 'arm')  && '__VAPOR_RUNTIME=docker-arm' || '' }}
