name: Build and test Docker multiplatform images

on:
  push:
    branches:
      - '**'
      - '!master'
    paths:
      - '!.github/workflows/*'
  pull_request:

jobs:
  docker:
    uses: ./.github/workflows/template-build-test.yml
    strategy:
      matrix:
        image: ['5.6', '7.1', '7.1-xdebug', '7.2', '7.2-xdebug', '7.3', '7.4', '7.4-xdebug', '8.0', '8.0-xdebug', '8.0-prod', '8.1', '8.1-xdebug', '8.1-prod', '8.2', '8.2-xdebug', '8.2-prod']
        platform: ['linux/amd64', 'linux/arm64']
    with:
      image: ${{ matrix.image }}
      platform: ${{ matrix.platform }}
  docker-vapor:
    uses: ./.github/workflows/template-build-test.yml
    with:
      image: '8.2-vapor'
      platform: 'linux/arm64'
      build-args: '__VAPOR_RUNTIME=docker-arm'
