name: Publish Docker multiplatform image

on:
  workflow_call:
    inputs:
      platform:
        required: true
        type: string
      image:
        required: true
        type: string
      build-args:
        required: false
        default: ''
        type: string

jobs:
  docker:
    runs-on: ubuntu-22.04
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:${{ inputs.image }}"
          platforms: "${{ inputs.platform }}"
          build-args: "${{ inputs.build-args }}"
          push: true
          tags: somosyampi/docker-php-fpm:${{ inputs.image }}